version: '3.9'

services:
  api:
    build: .
    container_name: finanzas360_api
    command: uvicorn main:app --host 0.0.0.0 --port ${APP_PORT:-8000}
    ports:
      - "${APP_PORT:-8000}:${APP_PORT:-8000}"
    env_file:
      - .env

    volumes:
      - .:/app